# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
    "

BBFILES_DYNAMIC += " \
    xilinx-tools:${LAYERDIR}/dynamic-layers/meta-xilinx-tools/recipes-*/*/*.bb \
    xilinx-tools:${LAYERDIR}/dynamic-layers/meta-xilinx-tools/recipes-*/*/*.bbappend \
    "

BBFILE_COLLECTIONS += "xilinx-contrib"
BBFILE_PATTERN_xilinx-contrib = "^${LAYERDIR}/"
BBFILE_PRIORITY_xilinx-contrib = "5"

LAYERSUMMARY_xilinx-contrib = "Community-contributed AMD Xilinx BSPs"
LAYERDESCRIPTION_xilinx-contrib = "Community / third-party BSP \
contribution layer carrying machines and recipes for AMD Xilinx \
hardware that is not part of the core supported set."

LAYERDEPENDS_xilinx-contrib = " \
    core \
    xilinx \
    "

LAYERSERIES_COMPAT_xilinx-contrib = "scarthgap"
