[Service]
# Continue if no input devices are present
# Enable debug messages and save to temporary log file
ExecStart=
ExecStart=/usr/bin/weston --modules=systemd-notify.so --continue-without-input --debug --log=/tmp/weston.log

[Install]
# Clear value so weston only starts when a display device is present
WantedBy=
