# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "amd-zephyr"
BBFILE_PATTERN_amd-zephyr = "^${LAYERDIR}/"
BBFILE_PRIORITY_amd-zephyr = "6"

LAYERDEPENDS_amd-zephyr = "\
    core \
    meta-python \
    zephyrcore \
    xilinx \
    xilinx-microblaze \
    virtualization-layer \
    "

LAYERSERIES_COMPAT_amd-zephyr = "scarthgap"
