#@TYPE: Machine
#@NAME: aarch64-tc
#@DESCRIPTION: Vitis baremetal toolchain machine: drives a multilib AArch64 (Cortex-A72/A53) cross-toolchain build for use with AMD Vitis embedded software flows. Not intended to boot a Linux image.

require conf/machine/include/machine-xilinx-qemu.inc
require conf/multilib.conf
require conf/machine/include/arm/armv8a/tune-cortexa72-cortexa53.inc
require conf/machine/include/baremetal-tc.conf

# Define all of the multilibs supported by this configuration
MULTILIB_GLOBAL_VARIANTS = "${@extend_variants(d,'MULTILIBS','multilib')}"
MULTILIBS = ""

# Base configuration
# CFLAGS:
DEFAULTTUNE = "cortexa72-cortexa53"
