#@TYPE: Machine
#@NAME: xenvmgicv3
#@DESCRIPTION: Yocto machine that builds Zephyr RTOS images for the Zephyr BOARD 'xenvm' running under a Xen hypervisor with a GICv3 interrupt controller (Arm aarch64 guest).

# Include tune-cortexa72-cortexa53.inc
require conf/machine/include/arm/armv8a/tune-cortexa72-cortexa53.inc

DEFAULTTUNE = "cortexa72-cortexa53"

# Zephyr RTOS settings
ZEPHYR_BOARD = "xenvm/xenvm/gicv3"
ARCH:xenvm = "aarch64"
DISTRO = "amd-zephyr"
