#@TYPE: Machine
#@NAME: versal-premium-generic
#@DESCRIPTION: Generic machine configuration for the AMD Versal Premium series (Versal SoC with AI Engine, targeting high-bandwidth networking and compute). Obsolete use versal-generic instead.

#### Preamble
MACHINEOVERRIDES =. "${@['', 'versal-premium-generic:']['versal-premium-generic' != '${MACHINE}']}"
#### Regular settings follow

require conf/machine/versal-generic.conf

MACHINE_FEATURES += "aie"

#### No additional settings should be after the Postamble
#### Postamble
PACKAGE_EXTRA_ARCHS:append = "${@['', ' versal_premium_generic']['versal-premium-generic' != "${MACHINE}"]}"

