#@TYPE: Machine
#@NAME: zynqmp-cg-generic
#@DESCRIPTION: Generic machine configuration for the dual-core (CG) variant of the AMD Zynq UltraScale+ MPSoC family (no GPU, no Video Codec Unit). Obsolete use zynqmp-generic instead.

#### Preamble
MACHINEOVERRIDES =. "${@['', 'zynqmp-cg-generic:']['zynqmp-cg-generic' != '${MACHINE}']}"
#### Regular settings follow

require conf/machine/zynqmp-generic.conf

#### No additional settings should be after the Postamble
#### Postamble
PACKAGE_EXTRA_ARCHS:append = "${@['', ' zynqmp_cg_generic']['zynqmp-cg-generic' != "${MACHINE}"]}"

